import type { Knex } from 'knex';

export async function up(knex: Knex): Promise<void> {
  // ── cv_harvest_batches: add batch_type and metrc_name ───────────────────
  //
  // In METRC, there are two distinct batch types created during the harvesting
  // phase:
  //
  //   Harvest Batch (HB): Full plant removal. The plant is cut. One per plant
  //     in the harvest window. Maps to event_type = 'final_harvest' events in
  //     cv_plant_harvest_events.
  //
  //   Manicure Batch (MB): Partial removal of usable (product) material while
  //     the plant remains alive. Multiple allowed per plant batch. Maps to
  //     event_type = 'partial_harvest' events in cv_plant_harvest_events.
  //
  // Both require batch.status = 'harvesting' — manicure is a harvest-phase
  // event, not a veg/flower trimming event.
  //
  // Minnesota OCM requires a specific naming format for both:
  //   HB: "Blue Dream | 05/21/2026 | HB | Auto"
  //   MB: "Blue Dream | 05/21/2026 | MB | Auto"
  //
  // metrc_name is generated by the app at creation time and stored immutably
  // so it survives strain/batch edits and matches what was submitted to METRC.
  //
  // batch_type defaults to 'harvest' so existing rows (which are all HB) are
  // correct without a data migration.

  await knex.schema.alterTable('cv_harvest_batches', (table) => {
    // 'harvest' | 'manicure'
    table.text('batch_type').notNullable().defaultTo('harvest');
    // MN OCM required name: "Strain | Date | HB|MB | Auto|Photo"
    // Computed and stored at creation; immutable after METRC sync.
    table.text('metrc_name').nullable();
  });
}

export async function down(knex: Knex): Promise<void> {
  await knex.schema.alterTable('cv_harvest_batches', (table) => {
    table.dropColumn('metrc_name');
    table.dropColumn('batch_type');
  });
}
